using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MedRecordWebApi.Data;
using SharedModels.Models;

namespace MedRecordWebApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class VisitsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public VisitsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Visits
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Visit>>> GetVisits()
        {
            // Include Patient data for context in the visit list
            return await _context.Visits.Include(v => v.Patient).ToListAsync();
        }

        // GET: api/Visits/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Visit>> GetVisit(int id)
        {
            // Include related prescription data when viewing a single visit
            var visit = await _context.Visits
                .Include(v => v.Patient)
                .Include(v => v.LabResults).ThenInclude(l => l.TestCatalog) // <-- Add this
                .Include(v => v.Prescriptions).ThenInclude(p => p.DrugCatalog) // <-- Add this
                .FirstOrDefaultAsync(v => v.VisitId == id);

            if (visit == null)
            {
                return NotFound();
            }

            return visit;
        }

        // PUT: api/Visits/5
        // Updates an existing visit record.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutVisit(int id, Visit visit)
        {
            if (id != visit.VisitId)
            {
                return BadRequest();
            }

            _context.Entry(visit).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VisitExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent(); // HTTP 204 No Content
        }

        // POST: api/Visits
        // Creates a new visit record. Requires a valid PatientId in the request body.
        [HttpPost]
        public async Task<ActionResult<Visit>> PostVisit(Visit visit)
        {
            // Optional: Basic check to ensure the associated patient exists before saving
            var patientExists = await _context.Patients.AnyAsync(p => p.PatientId == visit.PatientId);
            if (!patientExists && visit.PatientId != 0) // Allows posting a '0' ID for testing in Swagger if PatientId is generated by DB
            {
                return BadRequest("The specified PatientId does not exist.");
            }

            _context.Visits.Add(visit);
            await _context.SaveChangesAsync();

            // Returns HTTP 201 Created
            return CreatedAtAction("GetVisit", new { id = visit.VisitId }, visit);
        }

        // DELETE: api/Visits/5
        // Deletes a specific visit record.
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteVisit(int id)
        {
            var visit = await _context.Visits.FindAsync(id);
            if (visit == null)
            {
                return NotFound();
            }

            _context.Visits.Remove(visit);
            await _context.SaveChangesAsync();

            return NoContent(); // HTTP 204 No Content
        }

        // Helper method to check if a visit exists
        private bool VisitExists(int id)
        {
            return _context.Visits.Any(e => e.VisitId == id);
        }
    }
}
